### ISSUE TITLE
关于模型推断时间

### ISSUE THREAD

**Issue by cyccbxhl** [wanjinchang/SSH-TensorFlow#1]
你好，我下载了你公开的mobile和mobile_v2模型，然后使用你提供的tools/demo.py跑data/demo中的图片，发现推断时间需要一百多毫秒到几秒不等，并且推断时间与图片尺寸大小不相关，请问README中二十多毫秒是怎么测试的？
我的环境是：Tensorflow1.9+Ubuntu16.04+CUDA9.0+Nvidia GTX 1060 6G。

**Comment by wanjinchang** [comment]
你好！图片大小不固定是会影响模型推断时间的，我测试时限定了图片min_size=400, max_size=800,用同一张图片循环多次取推断时间平均值。代码中默认min_size=1200, max_size=1600,不同图片根据这个限定条件会resize成不同大小,所以推断时间与图片尺寸大小不相关。

**Comment by cyccbxhl** [comment]
好的，谢谢。
